# Database configuration for the Semantic Medallion Data Platform
# This file defines the PostgreSQL database resources on Digital Ocean:
# - A PostgreSQL database cluster
# - A database within the cluster
# - A database user for application access

# Create a PostgreSQL database cluster
# This is a managed PostgreSQL service provided by Digital Ocean
resource "digitalocean_database_cluster" "postgres" {
  # Name the cluster using project name and environment (e.g., "Semantic Data Platform-db-dev")
  name       = "${var.project_name}-db-${var.environment}"

  # Use PostgreSQL as the database engine
  engine     = "pg"

  # PostgreSQL version 15
  version    = "15"

  # Use the smallest available size to minimize costs
  # This size provides 1 vCPU and 1GB RAM at $15/month
  size       = "db-s-1vcpu-1gb"

  # Use the region specified in variables (default: lon1)
  region     = var.region

  # Single node cluster (no high availability)
  node_count = 1

  # Tag the cluster with the environment name for easier resource management
  tags = [var.environment]
}

# Create a database within the PostgreSQL cluster
# This will be the main database for the application
resource "digitalocean_database_db" "database" {
  # Reference the cluster ID from the cluster resource
  cluster_id = digitalocean_database_cluster.postgres.id

  # Set the database name
  name       = "semantic_data_platform"
}

# Create a database user for application access
# This user will be used by the application to connect to the database
resource "digitalocean_database_user" "user" {
  # Reference the cluster ID from the cluster resource
  cluster_id = digitalocean_database_cluster.postgres.id

  # Set the username
  name       = "semantic_app_user"

  # Note: The password is automatically generated by Digital Ocean
  # and can be accessed via the 'password' attribute
}
